create table if not exists public.feed_events (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles (id) on delete cascade,
  event_type text not null check (event_type in ('daily_practice', 'streak_milestone', 'accuracy_improved', 'problems_solved_milestone')),
  title text not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  event_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.feed_reactions (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.feed_events (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  reaction text not null check (reaction in ('clap', 'fire', 'insight')),
  created_at timestamptz not null default now(),
  unique (event_id, user_id, reaction)
);

create table if not exists public.feed_comments (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.feed_events (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.feed_events enable row level security;
alter table public.feed_reactions enable row level security;
alter table public.feed_comments enable row level security;

drop policy if exists "feed_events_select_authenticated" on public.feed_events;
create policy "feed_events_select_authenticated" on public.feed_events
for select
to authenticated
using (true);

drop policy if exists "feed_events_insert_self" on public.feed_events;
create policy "feed_events_insert_self" on public.feed_events
for insert
to authenticated
with check (auth.uid() = actor_id);

drop policy if exists "feed_events_update_self" on public.feed_events;
create policy "feed_events_update_self" on public.feed_events
for update
to authenticated
using (auth.uid() = actor_id)
with check (auth.uid() = actor_id);

drop policy if exists "feed_reactions_select_authenticated" on public.feed_reactions;
create policy "feed_reactions_select_authenticated" on public.feed_reactions
for select
to authenticated
using (true);

drop policy if exists "feed_reactions_insert_self" on public.feed_reactions;
create policy "feed_reactions_insert_self" on public.feed_reactions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "feed_reactions_delete_self" on public.feed_reactions;
create policy "feed_reactions_delete_self" on public.feed_reactions
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "feed_comments_select_authenticated" on public.feed_comments;
create policy "feed_comments_select_authenticated" on public.feed_comments
for select
to authenticated
using (true);

drop policy if exists "feed_comments_insert_self" on public.feed_comments;
create policy "feed_comments_insert_self" on public.feed_comments
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "feed_comments_delete_self" on public.feed_comments;
create policy "feed_comments_delete_self" on public.feed_comments
for delete
to authenticated
using (auth.uid() = user_id);
